/*
CREATE TABLE OTSNA (
    id smallserial NOT NULL,
    tank_id INTEGER NOT NULL PRIMARY KEY, 
    name TEXT NOT NULL, 
    tier INTEGER NOT NULL, 
    class TEXT NOT NULL, 
    nation TEXT NOT NULL, 
    isPrem BOOLEAN NOT NULL,

    owned INTEGER NOT NULL,
    avgBattles INTEGER NOT NULL,
    avgWinrate REAL NOT NULL,
    avgWN8 INTEGER NOT NULL,
    avgDamage INTEGER NOT NULL,
    avgFrags REAL NOT NULL,
    dmgRatio REAL NOT NULL,
    KD REAL NOT NULL,
    avgXP REAL NOT NULL,
    hits REAL NOT NULL,
    avgSpots REAL NOT NULL,
    armorEff REAL NOT NULL,
    ThreeMark REAL NOT NULL,
    ACE REAL NOT NULL,

    DPGpercentiles INTEGER[],
    WN8percentiles INTEGER[]
);

CREATE TABLE playerCount (
    id smallserial NOT NULL,
    name TEXT NOT NULL PRIMARY KEY, 
    numPlayers INTEGER NOT NULL
);

CREATE TABLE NAcurves (
    id smallserial NOT NULL,
    tank_id INTEGER NOT NULL PRIMARY KEY, 
    name TEXT NOT NULL, 
    WR42 REAL[], WR43 REAL[], WR44 REAL[], WR45 REAL[], WR46 REAL[], WR47 REAL[], WR48 REAL[], WR49 REAL[], WR50 REAL[], WR51 REAL[], WR52 REAL[], WR53 REAL[],
    WR54 REAL[], WR55 REAL[], WR56 REAL[], WR57 REAL[], WR58 REAL[], WR59 REAL[], WR60 REAL[], WR61 REAL[], WR62 REAL[], WR63 REAL[], WR64 REAL[], WR65 REAL[],

    WN200 INTEGER[], WN300 INTEGER[], WN400 INTEGER[], WN500 INTEGER[], WN600 INTEGER[], WN700 INTEGER[], WN800 INTEGER[], WN900 INTEGER[], WN1000 INTEGER[], WN1100 INTEGER[], 
    WN1200 INTEGER[], WN1300 INTEGER[], WN1400 INTEGER[], WN1500 INTEGER[], WN1600 INTEGER[], WN1700 INTEGER[], WN1800 INTEGER[], WN1900 INTEGER[], WN2000 INTEGER[], WN2100 INTEGER[], 
    WN2200 INTEGER[], WN2300 INTEGER[], WN2400 INTEGER[], WN2500 INTEGER[], WN2600 INTEGER[], WN2700 INTEGER[], WN2800 INTEGER[], WN2900 INTEGER[], WN3000 INTEGER[], WN3100 INTEGER[], 
    WN3200 INTEGER[], WN3300 INTEGER[], WN3400 INTEGER[], WN3500 INTEGER[]
);

CREATE TABLE tankDataNA (
    id smallserial NOT NULL,
    tank_id INTEGER NOT NULL PRIMARY KEY, 
    name TEXT NOT NULL, 
    tier INTEGER NOT NULL, 
    class TEXT NOT NULL, 
    nation TEXT NOT NULL, 
    isPrem BOOLEAN NOT NULL,

    owned INTEGER NOT NULL,
    battles INTEGER NOT NULL,
    wins INTEGER NOT NULL,
    damage BIGINT NOT NULL,
    damage_received BIGINT NOT NULL,

    WN8 BIGINT NOT NULL,

    frags INTEGER NOT NULL,
    xp BIGINT NOT NULL,
    survived INTEGER NOT NULL,
    hits INTEGER NOT NULL,
    shots INTEGER NOT NULL,

    tanking_factor real NOT NULL,
    def INTEGER NOT NULL,
    cap INTEGER NOT NULL,
    explosion_hits_received INTEGER NOT NULL,
    no_damage_direct_hits_received INTEGER NOT NULL,
    
	blocked BIGINT NOT NULL,
	spotted INTEGER NOT NULL,
    explosion_hits INTEGER NOT NULL,
    
    threeMark INTEGER NOT NULL,
    twoMark INTEGER NOT NULL,
    oneMark INTEGER NOT NULL,
    ace INTEGER NOT NULL,
    firstClass INTEGER NOT NULL,
    secondClass INTEGER NOT NULL,
    thirdClass INTEGER NOT NULL,

    DPG INTEGER[],
    WN8s INTEGER[],

    totalWN8 BIGINT,
    totalWinrate BIGINT
);

*/